# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trial/writer/bf_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atrial/writer/bf_data.proto\"E\n\nCustomData\x12\r\n\x05\x61rray\x18\x01 \x03(\x05\x12\x12\n\nhash_count\x18\x02 \x01(\x05\x12\x14\n\x0c\x61rray_length\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trial.writer.bf_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CUSTOMDATA']._serialized_start=30
  _globals['_CUSTOMDATA']._serialized_end=99
# @@protoc_insertion_point(module_scope)
