version: '3'
services:
  python-app:
    # build: ./trial  # Replace with the path to your Python app directory
    image: my-python-app:latest
    ports:
      - "8081:8080"  # Map container port 80 to host port 8080    
    environment:
      MYSQL_HOST: ${MYSQL_HOST} 
    depends_on:
      - mysql
    networks:
      - my-network
      
  mysql:
    image: my-own-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
